# =============================================================================
# CONFIGURAZIONE APPLICAZIONE SPRING BOOT - GESTIONE TAVOLI
# =============================================================================

spring.application.name=GestioneTavoli

# =============================================================================
# CONFIGURAZIONE SERVER WEB
# =============================================================================

server.port=8081

# =============================================================================
# CONFIGURAZIONE DATABASE POSTGRESQL
# =============================================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/bar
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================================================
# CONFIGURAZIONE JPA/HIBERNATE
# =============================================================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# =============================================================================
# CONFIGURAZIONE FLYWAY
# =============================================================================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=false

# =============================================================================
# CONFIGURAZIONE DATA.SQL
# =============================================================================

# spring.sql.init.mode=always
spring.sql.init.mode=never


# =============================================================================
# CONFIGURAZIONE SWAGGER/SPRINGDOC
# =============================================================================

springdoc.swagger-ui.path=/swagger-gestioneTavoli
springdoc.api-docs.path=/api-docs/json
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true
